// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BillContainer: typeof import('./src/components/BillContainer.vue')['default']
    BillItem: typeof import('./src/components/BillItem.vue')['default']
    CheckBox: typeof import('./src/components/m-input/CheckBox.vue')['default']
    DatePicker: typeof import('./src/components/DatePicker.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    InfoCard: typeof import('./src/components/InfoCard.vue')['default']
    MInput: typeof import('./src/components/m-input/m-input.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    NumberKeyboard: typeof import('./src/components/m-input/NumberKeyboard.vue')['default']
    Popup: typeof import('./src/components/Popup/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Topbar: typeof import('./src/components/Topbar.vue')['default']
  }
}
